version: 2.1
jobs:
  build:
    parameters:
      db_user:
        type: env_var_name
        default: TEST_DB_USERNAME
      db_password: 
        type: env_var_name
        default: DB_PASSWORD
      test_db_name:
        type: env_var_name
        default: TEST_DB_NAME
    docker:
      # specify the version you desire here
      - image: circleci/node:11.6.0
        environment:
          NODE_ENV: test

      # setup test database
      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: << parameters.db_user >>
          POSTGRES_DB: cmrc_db_test
          POSTGRES_PASSWORD: << parameters.db_password >>

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run:
          name: Run Tests
          command: npm run ci:test

      - store_artifacts:
          path: coverage

